FROM theatre_common AS auth_api_base

RUN mkdir -p requirements/auth_api logs/auth_api
COPY auth_api/requirements.txt \
    requirements/auth_api/requirements.txt    

RUN pip install --upgrade --no-cache-dir \
    -r requirements/auth_api/requirements.txt \
    --target site-packages

ENTRYPOINT ["tail", "-f", "/dev/null"]