FROM theatre_common AS gui_base

RUN mkdir -p requirements/gui/payment_api logs/gui
COPY gui/requirements.txt \
    requirements/gui/requirements.txt

RUN pip install --upgrade --no-cache-dir \
    -r requirements/gui/requirements.txt \
    --target site-packages

ENTRYPOINT ["tail", "-f", "/dev/null"]