FROM theatre_common AS email_worker_base

RUN mkdir -p requirements/notification/email-worker logs/notification/email-worker
COPY notification/email-worker/requirements.txt \
    requirements/notification/email-worker/requirements.txt

RUN pip install --upgrade --no-cache-dir \
    -r requirements/notification/email-worker/requirements.txt \
    --target site-packages

ENTRYPOINT ["tail", "-f", "/dev/null"]