#!/bin/bash
set -e

psql -v ON_ERROR_STOP=0 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE ROLE ${AUTH_DB_USER} WITH SUPERUSER LOGIN PASSWORD '${POSTGRES_PASSWORD}';
	CREATE ROLE ${NOTIFICATION_DB_USER} WITH SUPERUSER LOGIN PASSWORD '${POSTGRES_PASSWORD}';
	CREATE ROLE ${PAYMENT_DB_USER} WITH SUPERUSER LOGIN PASSWORD '${POSTGRES_PASSWORD}';
EOSQL
psql -v ON_ERROR_STOP=0 --username "${AUTH_DB_USER}" --dbname "$POSTGRES_DB" -c "CREATE DATABASE ${AUTH_DB};" || true
psql -v ON_ERROR_STOP=0 --username "${AUTH_DB_USER}" --dbname "$POSTGRES_DB" -c "CREATE DATABASE ${SENTRY_DB_NAME};" || true
psql -v ON_ERROR_STOP=0 --username "${NOTIFICATION_DB_USER}" --dbname "$POSTGRES_DB" -c "CREATE DATABASE ${NOTIFICATION_DB};" || true
psql -v ON_ERROR_STOP=0 --username "${PAYMENT_DB_USER}" --dbname "$POSTGRES_DB" -c "CREATE DATABASE ${PAYMENT_DB};" || true

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$AUTH_DB" <<-EOSQL
	CREATE SCHEMA IF NOT EXISTS ${AUTH_SCHEMA} AUTHORIZATION ${AUTH_DB_USER};
	ALTER ROLE ${AUTH_DB_USER} SET SEARCH_PATH=${AUTH_SCHEMA},public;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$NOTIFICATION_DB" <<-EOSQL
	CREATE SCHEMA IF NOT EXISTS ${NOTIFICATION_SCHEMA} AUTHORIZATION ${NOTIFICATION_DB_USER};
	ALTER ROLE ${NOTIFICATION_DB_USER} SET SEARCH_PATH=${NOTIFICATION_SCHEMA},public;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$PAYMENT_DB" <<-EOSQL
	CREATE SCHEMA IF NOT EXISTS ${PAYMENT_SCHEMA} AUTHORIZATION ${PAYMENT_DB_USER};
	ALTER ROLE ${PAYMENT_DB_USER} SET SEARCH_PATH=${PAYMENT_SCHEMA},public;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE SCHEMA IF NOT EXISTS ${POSTGRES_SCHEMA};
EOSQL