#!/bin/bash
set -e

psql -v ON_ERROR_STOP=0 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE ROLE ${AUTH_DB_USER} WITH SUPERUSER LOGIN PASSWORD '${POSTGRES_PASSWORD}';
EOSQL
psql -v ON_ERROR_STOP=1 --username "${AUTH_DB_USER}" --dbname "$POSTGRES_DB" -c "CREATE DATABASE ${AUTH_DB};" || true

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$AUTH_DB" <<-EOSQL
	CREATE SCHEMA IF NOT EXISTS ${AUTH_SCHEMA} AUTHORIZATION ${AUTH_DB_USER};
	ALTER ROLE ${AUTH_DB_USER} SET SEARCH_PATH=${AUTH_SCHEMA},public;
EOSQL
